### ISSUE TITLE
Store CSS with Customer Event

### ISSUE THREAD

**Issue by squishykid** [flamily/irs#101]
- [x] Take inputs: s3 filename and csss (int from 0 to 100) and store in db. (#108)
- [x] Need to design schema for creating the filename.
- [x] connect lambda - upload to s3 (#108)
- [x] trigger - get css - populate entry (#107).
